-- MySQL Script generated by MySQL Workbench
-- Mon Nov 29 20:04:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdpadocks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdpadocks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdpadocks` DEFAULT CHARACTER SET utf8 ;
USE `bdpadocks` ;

-- -----------------------------------------------------
-- Table `bdpadocks`.`chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpadocks`.`chef` (
  `idchef` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `salario` FLOAT NOT NULL,
  PRIMARY KEY (`idchef`),
  UNIQUE INDEX `idtable1_UNIQUE` (`idchef` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdpadocks`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpadocks`.`cliente` (
  `idcliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
